config:
BOLD_TSV: resources/BOLD_Public.03-Jan-2025.tsv
#BOLD_TSV: resources/BOLD_Public.15-Nov-2024-COI-5P_subset_10k.tsv
#CRITERIA: "COLLECTION_DATE COLLECTORS COORD COUNTRY IDENTIFIER ID_METHOD INSTITUTION MUSEUM_ID PUBLIC_VOUCHER SEQ_QUALITY SITE SPECIES_ID TYPE_SPECIMEN"
#CRITERIA: "COLLECTION_DATE COLLECTORS COORD HAS_IMAGE IDENTIFIER ID_METHOD INSTITUTION MUSEUM_ID PUBLIC_VOUCHER SEQ_QUALITY SITE SPECIES_ID TYPE_SPECIMEN"
CRITERIA: "HAS_IMAGE"
TARGET_LIST: resources/all_specs_and_syn.csv
PROJECT_NAME: "bold-curation_3-Jan-2025"
TAXON_LEVEL: "species"
KINGDOM: "Animalia"
LOG_LEVEL: "INFO"
IMAGE_URL: True  # Flag to specify whether the image_url file should be generated